/* PICHICATA — banco de piezas modulares
   Los eventos no traen texto fijo: sortean piezas de acá y las ensamblan.
   unlock: null = disponible desde la primera run. */

window.PICHI = window.PICHI || {};

PICHI.ESCENARIOS = [
  // --- base: urbano / precario ---
  { id: "esc_terraza_constitucion", nombre: "la terraza de una pensión en Constitución", detalle: "hay una pileta de lona con agua verde y un perro que no es de nadie", tags: ["urbano", "precario", "noche", "ritual"], unlock: null },
  { id: "esc_plaza_seca", nombre: "una plaza sin pasto de Villa Luro", detalle: "los juegos están pintados de un naranja que ya no existe en la naturaleza", tags: ["urbano", "publico", "dia"], unlock: null },
  { id: "esc_depto_prestado", nombre: "un monoambiente prestado en Almagro", detalle: "el ventilador de techo hace un clic cada vuelta y media", tags: ["urbano", "interior", "precario"], unlock: null },
  { id: "esc_galpon_barracas", nombre: "un galpón reciclado en Barracas", detalle: "cuelgan telas de colores para tapar que sigue siendo un galpón", tags: ["urbano", "ritual", "precario"], unlock: null },
  { id: "esc_bar_de_viejos", nombre: "un bar de viejos en Once", detalle: "el televisor está en un canal de subastas y nadie lo mira", tags: ["urbano", "social", "dia"], unlock: null },
  { id: "esc_baño_boliche", nombre: "el baño de un boliche de Palermo", detalle: "el secador de manos ruge como una bestia herida", tags: ["urbano", "interior", "noche", "quimico"], unlock: null },
  { id: "esc_azotea_amanecer", nombre: "una azotea con vista a las vías del San Martín", detalle: "el cielo está de ese color que no es día ni noche y nadie nombró todavía", tags: ["urbano", "noche", "trip"], unlock: null },
  { id: "esc_local_vacio", nombre: "un local que fue verdulería y ahora dice CENTRO HOLÍSTICO en fibrón", detalle: "todavía hay una balanza colgada del techo", tags: ["urbano", "ritual", "precario", "chanta"], unlock: null },
  { id: "esc_colectivo_60", nombre: "el fondo de un 60 a las tres de la mañana", detalle: "el piso está mojado y nadie sabe de qué", tags: ["urbano", "transito", "noche"], unlock: null },
  { id: "esc_pasillo_hotel", nombre: "el pasillo de un hotel familiar sobre Rivadavia", detalle: "la alfombra tiene un dibujo que si lo mirás mucho se mueve", tags: ["urbano", "interior", "trip"], unlock: null },
  { id: "esc_cancha_baby", nombre: "una canchita de baby fútbol clausurada", detalle: "hay un arco solo, el otro se lo llevaron y nadie preguntó", tags: ["urbano", "publico", "noche"], unlock: null },
  { id: "esc_feria_americana", nombre: "una feria americana en una vereda de Flores", detalle: "todo cuesta lo mismo y nada sirve", tags: ["urbano", "social", "dia", "comercio"], unlock: null },
  { id: "esc_lavadero", nombre: "un lavadero automático abierto 24 horas", detalle: "el zumbido de los tambores hace de mantra sin cobrar nada", tags: ["urbano", "interior", "noche", "ritual"], unlock: null },
  { id: "esc_esquina_kiosco", nombre: "la esquina del kiosco que atiende por la ventanita", detalle: "hay tres pibes en bici que están ahí siempre, en cualquier horario, siempre", tags: ["urbano", "comercio", "social"], unlock: null },
  { id: "esc_hospital_guardia", nombre: "la sala de espera de una guardia a las cinco de la mañana", detalle: "el tubo fluorescente parpadea con un ritmo que no es de este planeta", tags: ["urbano", "interior", "noche", "cuerpo"], unlock: null },

  // --- A1: circuito conurbano ---
  { id: "esc_quinta_moreno", nombre: "una quinta alquilada en Moreno", detalle: "la pileta tiene una rana muerta flotando en el mismo lugar desde ayer", tags: ["conurbano", "ritual", "precario"], unlock: "A1" },
  { id: "esc_asado_sin_carne", nombre: "un asado en un terreno de Rafael Castillo", detalle: "hay parrilla, hay fuego, hay siete personas y no hay carne", tags: ["conurbano", "social", "precario"], unlock: "A1" },
  { id: "esc_estacion_haedo", nombre: "el andén 2 de Haedo pasada la medianoche", detalle: "un tipo canta boleros con un parlante bluetooth al 3%", tags: ["conurbano", "transito", "noche"], unlock: "A1" },
  { id: "esc_club_barrio", nombre: "el buffet de un club de barrio de Villa Madero", detalle: "en la pared hay una foto de un equipo de 1978 y todos miran a otro lado", tags: ["conurbano", "social", "ritual"], unlock: "A1" },
  { id: "esc_zanjon", nombre: "el borde de un zanjón en San Justo", detalle: "el agua tiene una película arcoíris que es hermosa por los motivos equivocados", tags: ["conurbano", "precario", "trip"], unlock: "A1" },
  { id: "esc_taller_mecanico", nombre: "un taller mecánico cerrado que abre de noche para otras cosas", detalle: "hay un almanaque de 2011 y un altar a San La Muerte al lado del compresor", tags: ["conurbano", "interior", "ritual"], unlock: "A1" },
  { id: "esc_terminal_liniers", nombre: "la terminal de micros de Liniers", detalle: "huele a facturas viejas y a gasoil y las dos cosas dan hambre", tags: ["conurbano", "transito", "dia"], unlock: "A1" },

  // --- A6: escenarios remotos ---
  { id: "esc_sierras_cordoba", nombre: "una casa de piedra en las sierras de Córdoba", detalle: "no hay señal y eso al principio parece una virtud", tags: ["remoto", "ritual", "naturaleza"], unlock: "A6" },
  { id: "esc_ruta_9", nombre: "la banquina de la ruta 9 a la altura de nada", detalle: "hay un santuario de botellas de plástico y un camión que no frena", tags: ["remoto", "transito", "naturaleza"], unlock: "A6" },
  { id: "esc_monte_chaco", nombre: "un claro en el monte chaqueño", detalle: "los bichos hacen un ruido tan parejo que después de un rato es silencio", tags: ["remoto", "naturaleza", "ritual", "noche"], unlock: "A6" },
  { id: "esc_dique_seco", nombre: "el lecho de un dique que se secó en 2019", detalle: "se ve el pueblo que taparon cuando lo llenaron, y las paredes siguen ahí", tags: ["remoto", "naturaleza", "trip"], unlock: "A6" },
  { id: "esc_delta_isla", nombre: "una casilla sobre pilotes en el Delta", detalle: "el agua marrón sube y baja como si respirara y en realidad respira", tags: ["remoto", "naturaleza", "ritual"], unlock: "A6" },
  { id: "esc_salar", nombre: "el borde de un salar en Jujuy a las dos de la tarde", detalle: "no hay sombra en ninguna dirección disponible", tags: ["remoto", "naturaleza", "trip", "dia"], unlock: "A6" },
  { id: "esc_cabaña_bariloche", nombre: "una cabaña de alquiler fuera de temporada en El Bolsón", detalle: "el dueño dejó una nota que dice NO USAR LA ESTUFA subrayado tres veces", tags: ["remoto", "interior", "naturaleza"], unlock: "A6" },
  { id: "esc_capilla_abandonada", nombre: "una capilla sin techo en el medio del campo", detalle: "las palomas hicieron nido en el lugar del santo", tags: ["remoto", "ritual", "naturaleza"], unlock: "A6" },
  { id: "esc_camping_temporada", nombre: "un camping municipal en marzo", detalle: "quedan las marcas de las carpas en el pasto, como fantasmas prolijos", tags: ["remoto", "naturaleza", "social"], unlock: "A6" },
  { id: "esc_mina_abandonada", nombre: "la boca de una mina abandonada en Catamarca", detalle: "del fondo sale un aire fresco que no debería estar fresco", tags: ["remoto", "trip", "naturaleza"], unlock: "A6" },
  { id: "esc_pueblo_fantasma", nombre: "un pueblo de la pampa con doce habitantes censados", detalle: "el almacén abre cuando el dueño se acuerda", tags: ["remoto", "social", "dia"], unlock: "A6" },
  { id: "esc_termas", nombre: "unas termas semi clandestinas atrás de un alambrado cortado", detalle: "el agua sale a cuarenta y dos grados y huele a fósforo", tags: ["remoto", "naturaleza", "cuerpo"], unlock: "A6" },

  // --- astral / trip profundo (A4) ---
  { id: "esc_pasillo_infinito", nombre: "un pasillo que es el pasillo de tu casa de la infancia pero más largo", detalle: "las puertas están todas del mismo lado", tags: ["astral", "trip", "interior"], unlock: "A4" },
  { id: "esc_sala_espera_blanca", nombre: "una sala de espera sin puertas donde todos tienen tu cara", detalle: "hay revistas de 1997 y están todas en blanco", tags: ["astral", "trip"], unlock: "A4" },
  { id: "esc_supermercado_vacio", nombre: "un supermercado enorme sin nadie y con la música puesta", detalle: "todas las góndolas tienen el mismo producto y el producto no tiene nombre", tags: ["astral", "trip", "interior"], unlock: "A4" },
  { id: "esc_playa_negra", nombre: "una playa de arena negra donde el mar no hace ruido", detalle: "la espuma queda quieta cuando llega, como pintada", tags: ["astral", "trip", "naturaleza"], unlock: "A4" },
  { id: "esc_cocina_de_tu_vieja", nombre: "la cocina de tu vieja, exacta, incluso el imán del delivery", detalle: "está todo bien salvo que la ventana da a un lugar que no es el patio", tags: ["astral", "trip", "interior"], unlock: "A4" },
  { id: "esc_ascensor_infinito", nombre: "un ascensor que baja más pisos de los que tiene el edificio", detalle: "el tablero llega hasta el 14 y sigue bajando", tags: ["astral", "trip", "interior"], unlock: "A4" },
  { id: "esc_terminal_vacia", nombre: "una terminal de micros sin un solo pasajero y con todos los andenes ocupados", detalle: "los motores están encendidos y las cabinas vacías", tags: ["astral", "trip", "transito"], unlock: "A4" },
  { id: "esc_aula_sin_nadie", nombre: "el aula de séptimo grado, con tu banco y tu nombre tallado", detalle: "el pizarrón tiene la fecha de hoy escrita con tu letra de nene", tags: ["astral", "trip", "interior"], unlock: "A4" },
  { id: "esc_patio_infancia", nombre: "el patio de la casa donde te criaste, en la misma tarde de siempre", detalle: "la ropa está colgada y hace treinta años que no se seca", tags: ["astral", "trip", "naturaleza"], unlock: "A4" },
  { id: "esc_vereda_repetida", nombre: "una cuadra de tu barrio que se repite cada vez que llegás a la esquina", detalle: "el mismo kiosco, el mismo perro, la misma bolsa de basura", tags: ["astral", "trip", "urbano"], unlock: "A4" },
  { id: "esc_cuarto_sin_puerta", nombre: "un cuarto de tres por tres sin puertas y con la luz prendida", detalle: "hay una silla y la silla está tibia", tags: ["astral", "trip", "interior"], unlock: null },
  { id: "esc_pasillo_sanatorio", nombre: "el pasillo de un sanatorio a las cuatro y doce de la mañana", detalle: "las camillas están hechas y no hay nadie de guardia", tags: ["astral", "trip", "interior", "cuerpo"], unlock: null }
];

PICHI.PERSONAJES = [
  // --- base ---
  { id: "per_sergio", nombre: "Sergio", mote: "el Iluminado de Lanús", desc: "un tipo de sesenta con campera de River y tres cuentas de mala en la muñeca", tags: ["guru", "chanta", "porteño"], unlock: null },
  { id: "per_yesica", nombre: "Yésica", mote: "la que canta los ícaros", desc: "tiene una voz increíble y una teoría sobre las vacunas que arruina todo", tags: ["guru", "ritual", "social"], unlock: null },
  { id: "per_tincho", nombre: "Tincho", mote: "el que trajo la merca al retiro", desc: "veintiocho años, riñonera, jamás en su vida sintió culpa", tags: ["lumpen", "quimico", "social"], unlock: null },
  { id: "per_norma", nombre: "Norma", mote: "reikista jubilada", desc: "sesenta y cuatro, manos calientes de verdad, cero paciencia", tags: ["guru", "social", "cuidadora"], unlock: null },
  { id: "per_flaco", nombre: "el Flaco", mote: "que estuvo en la India dos meses en 2004", desc: "no terminó una sola frase en su vida y aun así se le entiende todo", tags: ["guru", "chanta", "trip"], unlock: null },
  { id: "per_kiosquero", nombre: "Rubén", mote: "el de la ventanita", desc: "no se le ve la cara, solo las manos y un tatuaje de un delfín", tags: ["comercio", "lumpen"], unlock: null },
  { id: "per_dai", nombre: "Dai", mote: "que hace un año que no duerme bien", desc: "veintidós, tatuajes hechos por amigos, la persona más honesta del retiro", tags: ["social", "quimico", "joven"], unlock: null },
  { id: "per_coach", nombre: "Maxi Ferreyra", mote: "coach de abundancia cuántica", desc: "camisa blanca, dientes de otro país, habla de energía y quiere decir plata", tags: ["chanta", "guru", "comercio"], unlock: null },
  { id: "per_perro", nombre: "un perro marrón", mote: "sin collar y con criterio", desc: "te sigue tres cuadras y después decide que no", tags: ["animal", "misterio"], unlock: null },
  { id: "per_taxista", nombre: "Ojeda", mote: "el remisero que sabe todo", desc: "cincuenta y tantos, escucha AM, tiene una explicación completa del universo", tags: ["social", "porteño", "transito"], unlock: null },
  { id: "per_pibe_pelota", nombre: "un nene", mote: "con una pelota media desinflada", desc: "hace preguntas que deberían estar prohibidas por su nivel de dificultad", tags: ["joven", "misterio", "inocente"], unlock: null },
  { id: "per_encargado", nombre: "el encargado del edificio", mote: "que ve todo y no dice nada", desc: "trapo al hombro, ojos de haber visto morir cuatro inquilinos", tags: ["social", "porteño", "testigo"], unlock: null },
  { id: "per_monja", nombre: "sor Alicia", mote: "que reparte guiso los jueves", desc: "ochenta kilos de bondad práctica y ni un gramo de misticismo", tags: ["cuidadora", "social", "religioso"], unlock: null },
  { id: "per_gaby", nombre: "Gaby", mote: "que estudia psicología y lo aclara siempre", desc: "toma notas de todo lo que pasa, incluso cuando pasa mal", tags: ["social", "joven", "esceptico"], unlock: null },
  { id: "per_hermano", nombre: "tu hermano", mote: "que no habla del tema", desc: "vino a buscarte una vez y no lo vas a olvidar nunca", tags: ["familia", "social"], unlock: null },
  { id: "per_dealer_filosofo", nombre: "Cachito", mote: "que vende y también opina", desc: "leyó medio libro de Nietzsche en 2009 y lo administra con inteligencia", tags: ["lumpen", "comercio", "quimico"], unlock: null },
  { id: "per_señora_edificio", nombre: "una señora del tercero", mote: "que golpea el techo con un palo", desc: "no duerme desde que se jubiló y lo convirtió en una vocación", tags: ["social", "testigo"], unlock: null },
  { id: "per_musico", nombre: "Pipa", mote: "que toca el tambor y no para nunca", desc: "sostiene que el ritmo cura y en algún sentido tiene razón", tags: ["ritual", "social", "musico"], unlock: null },
  { id: "per_vos_de_19", nombre: "vos, a los diecinueve", mote: "con una seguridad que nunca tuviste", desc: "usa la ropa que usabas y dice las cosas que ahora te dan vergüenza", tags: ["astral", "ego"], unlock: null },
  { id: "per_enfermera", nombre: "una enfermera del turno noche", mote: "que ya vio esto ochenta veces", desc: "no te juzga, y eso te desarma más que si te juzgara", tags: ["cuidadora", "cuerpo"], unlock: null },

  // --- A5: fauna espiritual ---
  { id: "per_swami_gonzalez", nombre: "Swami Gonzalez", mote: "antes Rubén Gonzalez, de Ramos Mejía", desc: "túnica naranja impecable y acento de Ramos que no se le va ni con mantras", tags: ["guru", "chanta", "conurbano"], unlock: "A5" },
  { id: "per_chamana", nombre: "doña Rufina", mote: "que sí sabe", desc: "no vende nada, no explica nada, y te mira como si ya supiera cómo termina", tags: ["guru", "ritual", "autentico"], unlock: "A5" },
  { id: "per_pibe_cristal", nombre: "Lautaro", mote: "niño índigo de 34 años", desc: "su mamá le dijo a los seis que era especial y nadie lo contradijo nunca", tags: ["chanta", "trip", "social"], unlock: "A5" },
  { id: "per_expolicia", nombre: "Beto", mote: "ex cana devenido en terapeuta corporal", desc: "sus masajes son excelentes y aterradores en partes iguales", tags: ["social", "cuerpo", "turbio"], unlock: "A5" },
  { id: "per_astrologa", nombre: "Ceci", mote: "astróloga con turnos hasta noviembre", desc: "tiene una lista de gente a la que le arruinó una relación con una lectura", tags: ["guru", "comercio", "social"], unlock: "A5" },
  { id: "per_gemelas", nombre: "las gemelas Ríos", mote: "que hablan al mismo tiempo", desc: "cuarenta y pico, canalizan a la misma entidad y a veces se contradicen", tags: ["ritual", "trip", "social"], unlock: "A5" },
  { id: "per_veterano", nombre: "don Elio", mote: "que estuvo en un retiro de verdad en el 74", desc: "compara todo con eso y no le gusta nada de lo que ve ahora", tags: ["guru", "social", "veterano"], unlock: "A5" },
  { id: "per_influencer", nombre: "Sol", mote: "que documenta su despertar para 40 mil personas", desc: "pide silencio para grabar el silencio", tags: ["chanta", "social", "joven"], unlock: "A5" },
  { id: "per_cocinero", nombre: "el Ruso", mote: "que cocina para el retiro y odia a todos", desc: "hace la mejor comida del país y te lo dice mientras te sirve", tags: ["social", "cuidadora", "cascarrabias"], unlock: "A5" },
  { id: "per_traductor", nombre: "Nacho", mote: "que traduce al maestro que habla portugués", desc: "no sabe portugués, pero improvisa con una confianza notable", tags: ["chanta", "ritual", "social"], unlock: "A5" },
  { id: "per_viuda", nombre: "Marta", mote: "que vino a hablar con su marido muerto", desc: "no le interesa iluminarse, le interesa una sola conversación de cinco minutos", tags: ["social", "duelo"], unlock: "A5" },
  { id: "per_cadete", nombre: "un cadete de delivery", mote: "que llegó al medio de la ceremonia", desc: "tiene tres pedidos más y una calma zen absoluta", tags: ["lumpen", "social", "transito"], unlock: "A5" },
  { id: "per_gato", nombre: "un gato negro del galpón", mote: "que se sienta siempre en el centro del círculo", desc: "no lo alimenta nadie y está gordo, sacá tus conclusiones", tags: ["animal", "misterio", "ritual"], unlock: "A5" },
  { id: "per_contador", nombre: "Fabián", mote: "contador en licencia psiquiátrica", desc: "sabe exactamente cuánto factura el retiro y no puede dejar de decirlo", tags: ["social", "esceptico", "turbio"], unlock: "A5" },

  /* --- caras del ego y del plano astral (ensanchan el pool de A4/A9) ---
     OJO: estas piezas llevan SOLO los tags "ego" y "astral" a propósito.
     Si les agregás tags genéricos (joven, familia, guru...) se filtran a
     eventos mundanos y aparece "vos, a los siete" comprando en un kiosco. */
  // --- fauna (los eventos con slot "animal" necesitan de dónde elegir) ---
  { id: "per_caballo_flaco", nombre: "un caballo flaco atado a un poste", mote: "que ya vio todo", desc: "tiene las costillas contadas y una calma que no se explica", tags: ["animal", "naturaleza"], unlock: null },
  { id: "per_carancho", nombre: "un carancho", mote: "parado en el poste de luz", desc: "no se mueve y te sigue con la cabeza cuando caminás", tags: ["animal", "misterio"], unlock: null },
  { id: "per_perra_cria", nombre: "una perra con cría", mote: "abajo de un auto", desc: "no te deja acercarte y no se va, las dos cosas a la vez", tags: ["animal"], unlock: null },
  { id: "per_serpiente", nombre: "una serpiente que no es de esta provincia", mote: "y lo sabe", desc: "está enroscada en un lugar donde no puede haber una serpiente", tags: ["animal", "astral", "misterio"], unlock: "A4" },
  { id: "per_jaguar", nombre: "un jaguar", mote: "a mil kilómetros de donde debería estar", desc: "no pestañea y no tiene ningún apuro", tags: ["animal", "astral"], unlock: "A4" },

  { id: "per_vos_de_7", nombre: "vos, a los siete", mote: "esperando algo que no llegó", desc: "está sentado en el borde de la cama y no está durmiendo", tags: ["ego", "astral"], unlock: null },
  { id: "per_vos_exitoso", nombre: "vos, el que se quedó en el trabajo", mote: "el que no vino", desc: "mejor cara, mejor ropa y una tranquilidad que se compra", tags: ["ego", "astral"], unlock: null },
  { id: "per_voz_sin_cuerpo", nombre: "una voz sin cuerpo", mote: "que usa tu tono de hablar por teléfono", desc: "viene de una dirección que se corre cada vez que la buscás", tags: ["ego", "astral"], unlock: null },
  { id: "per_vos_manana", nombre: "vos, mañana a la mañana", mote: "el que va a tener que resolver esto", desc: "tiene ojeras y una lista de cosas que vas a dejarle", tags: ["ego", "astral"], unlock: null },
  { id: "per_vos_de_70", nombre: "vos, a los setenta y cuatro", mote: "si llegás", desc: "no te reprocha nada y por eso mismo es insoportable", tags: ["ego", "astral"], unlock: "A4" },
  { id: "per_madre_joven", nombre: "tu vieja, más joven que vos ahora", mote: "que todavía no sabe nada de esto", desc: "está lavando algo y no se da vuelta", tags: ["astral"], unlock: "A4" },
  { id: "per_maestro_impecable", nombre: "un maestro impecable", mote: "demasiado impecable", desc: "la voz, la mirada, las frases, el silencio: todo perfecto, y eso es el problema", tags: ["ego", "astral"], unlock: "A4" },
  { id: "per_el_que_dejaste", nombre: "el que dejaste esperando", mote: "en la versión exacta de esa noche", desc: "tiene el teléfono en la mano con tu nombre en la pantalla", tags: ["ego", "astral"], unlock: "A9" },
  { id: "per_doble", nombre: "tu doble", mote: "que se adelanta medio segundo", desc: "hace lo que vos vas a hacer, un poco antes, y mejor", tags: ["ego", "astral"], unlock: "A9" }
];

PICHI.COMPLICACIONES = [
  { id: "cmp_falta_uno", texto: "falta uno del grupo y nadie se acuerda cómo se llamaba", tags: ["social", "misterio"], hint: { paranoia: 4 }, unlock: null },
  { id: "cmp_llueve", texto: "empieza a llover con esa lluvia fina que moja más", tags: ["clima", "cuerpo"], hint: { aguante: -3 }, unlock: null },
  { id: "cmp_cumbia", texto: "de un patio vecino sale una cumbia a un volumen incompatible con la introspección", tags: ["social", "ruido"], hint: {}, unlock: null },
  { id: "cmp_celular_suena", texto: "tu celular vibra con un número que conocés y no querés atender", tags: ["social", "personal"], hint: { paranoia: 5 }, unlock: null },
  { id: "cmp_alguien_llora", texto: "atrás alguien llora hace veinte minutos y ya empieza a ser una decisión", tags: ["social", "emocional"], hint: {}, unlock: null },
  { id: "cmp_sin_agua", texto: "se cortó el agua y hay once personas que van a necesitar agua", tags: ["precario", "cuerpo"], hint: { aguante: -4 }, unlock: null },
  { id: "cmp_perro_ladra", texto: "un perro ladra a algo que no está y no para", tags: ["ruido", "misterio"], hint: { paranoia: 6 }, unlock: null },
  { id: "cmp_olor_raro", texto: "hay un olor dulce y podrido que nadie nombra por educación", tags: ["cuerpo", "misterio"], hint: {}, unlock: null },
  { id: "cmp_no_hay_luz", texto: "se corta la luz de la manzana entera y todos aplauden, no se sabe por qué", tags: ["precario", "social"], hint: {}, unlock: null },
  { id: "cmp_alguien_filma", texto: "alguien está filmando todo con el celu y dice que es para el archivo", tags: ["social", "vigilancia"], hint: { paranoia: 8 }, unlock: null },
  { id: "cmp_plata_falta", texto: "falta plata de un bolso y todavía nadie lo dijo en voz alta", tags: ["social", "conflicto"], hint: { paranoia: 10 }, unlock: null },
  { id: "cmp_hambre", texto: "hace catorce horas que nadie come nada sólido", tags: ["cuerpo", "precario"], hint: { aguante: -6 }, unlock: null },
  { id: "cmp_sirena", texto: "pasa una sirena, se aleja, vuelve, y se queda", tags: ["policial", "ruido"], hint: { paranoia: 12 }, unlock: null },
  { id: "cmp_vomito_previo", texto: "hay vómito en un rincón desde antes de que llegaras", tags: ["cuerpo", "precario"], hint: {}, unlock: null },
  { id: "cmp_tambor", texto: "el tambor no para y ya dejó de ayudar", tags: ["ruido", "ritual"], hint: { paranoia: 5 }, unlock: null },
  { id: "cmp_frio", texto: "bajó la temperatura de golpe y nadie trajo abrigo porque era verano a las siete", tags: ["clima", "cuerpo"], hint: { aguante: -5 }, unlock: null },
  { id: "cmp_conocido", texto: "hay alguien que te conoce de antes y todavía no te saludó", tags: ["social", "personal"], hint: { paranoia: 7 }, unlock: null },
  { id: "cmp_reloj_no_avanza", texto: "mirás la hora dos veces con diez minutos de diferencia y da lo mismo", tags: ["trip", "misterio"], hint: {}, unlock: null },
  { id: "cmp_todos_te_miran", texto: "todos hablan de vos en la parte de la charla que no escuchás", tags: ["social", "paranoia"], hint: { paranoia: 12 }, unlock: null },
  { id: "cmp_promesa", texto: "le prometiste a alguien que hoy no ibas a hacer justamente esto", tags: ["personal", "karma"], hint: { karma: -2 }, unlock: null },
  { id: "cmp_bebe_llora", texto: "en el departamento de al lado llora un bebé con una constancia admirable", tags: ["ruido", "social"], hint: {}, unlock: null },
  { id: "cmp_sangre_nariz", texto: "te sangra un poco la nariz y hacés como que no", tags: ["cuerpo", "quimico"], hint: { aguante: -4 }, unlock: null },
  { id: "cmp_mucha_gente", texto: "hay el doble de gente de la que se había hablado", tags: ["social", "precario"], hint: { paranoia: 6 }, unlock: null },
  { id: "cmp_nadie_vino", texto: "iban a venir doce y vinieron tres, contándote", tags: ["social", "melancolia"], hint: {}, unlock: null },
  { id: "cmp_zapatilla", texto: "perdiste una zapatilla en algún momento de las últimas dos horas", tags: ["absurdo", "cuerpo"], hint: {}, unlock: null },

  // --- A7: complicaciones cósmicas ---
  { id: "cmp_dos_lunas", texto: "hay dos lunas y una de las dos claramente está de más", tags: ["trip", "astral"], hint: { paranoia: 10 }, unlock: "A7" },
  { id: "cmp_tu_voz", texto: "escuchás tu propia voz diciendo cosas que todavía no dijiste", tags: ["trip", "astral"], hint: { paranoia: 14 }, unlock: "A7" },
  { id: "cmp_sin_reflejo", texto: "en el vidrio te falta el reflejo y decidís no comentarlo", tags: ["trip", "astral"], hint: { paranoia: 12 }, unlock: "A7" },
  { id: "cmp_todos_lo_mismo", texto: "las últimas cuatro personas te dijeron exactamente la misma frase", tags: ["trip", "astral"], hint: { paranoia: 11 }, unlock: "A7" },
  { id: "cmp_texto_se_mueve", texto: "las palabras escritas en las paredes se reacomodan cuando dejás de mirarlas", tags: ["trip", "astral"], hint: { paranoia: 9 }, unlock: "A7" },
  { id: "cmp_animal_habla", texto: "un animal te dice una cosa breve, correcta y muy incómoda", tags: ["trip", "astral"], hint: { conciencia: 3 }, unlock: "A7" },
  { id: "cmp_hueco_memoria", texto: "hay veinte minutos de hoy que no están en ningún lado", tags: ["trip", "quimico"], hint: { paranoia: 13 }, unlock: "A7" },
  { id: "cmp_luz_propia", texto: "una persona del grupo emite una luz tenue que nadie más registra", tags: ["astral", "ritual"], hint: { conciencia: 4 }, unlock: "A7" },
  { id: "cmp_sabor_metal", texto: "todo tiene gusto a moneda vieja, incluso el aire", tags: ["cuerpo", "quimico"], hint: {}, unlock: "A7" },
  { id: "cmp_deja_vu", texto: "ya viviste este momento exacto y la vez anterior salió mal", tags: ["trip", "astral"], hint: { paranoia: 10 }, unlock: "A7" },
  { id: "cmp_manos_ajenas", texto: "tus manos se mueven medio segundo antes de que vos decidas moverlas", tags: ["trip", "cuerpo"], hint: { paranoia: 12 }, unlock: "A7" },
  { id: "cmp_alguien_de_mas", texto: "los contás y sale uno más de los que hay", tags: ["trip", "astral", "misterio"], hint: { paranoia: 15 }, unlock: "A7" },
  { id: "cmp_musica_interna", texto: "hay una música que viene claramente de adentro de tu cabeza y es buena", tags: ["trip", "quimico"], hint: { conciencia: 3 }, unlock: "A7" },
  { id: "cmp_ojos_cerrados", texto: "con los ojos cerrados ves mejor la habitación que con los ojos abiertos", tags: ["trip", "astral"], hint: { conciencia: 4 }, unlock: "A7" }
];

PICHI.OBJETOS_MENCION = [
  { id: "obj_termo", texto: "un termo abollado con la tapa atada con alambre", tags: ["precario"] },
  { id: "obj_mala", texto: "una mala de 108 cuentas con dos cuentas de menos", tags: ["ritual"] },
  { id: "obj_encendedor", texto: "un encendedor rosa transparente sin gas", tags: ["quimico"] },
  { id: "obj_libro", texto: "un libro de tapa dura sobre chakras con el lomo intacto", tags: ["chanta"] },
  { id: "obj_botella", texto: "una botella de vino de litro con la etiqueta arrancada", tags: ["quimico"] },
  { id: "obj_cuenco", texto: "un cuenco tibetano hecho en Villa Celina", tags: ["ritual", "chanta"] },
  { id: "obj_pipa", texto: "una pipa de manzana que se hizo alguien a las cuatro de la mañana", tags: ["quimico"] },
  { id: "obj_estampita", texto: "una estampita del Gauchito plastificada con cinta de embalar", tags: ["religioso"] },
  { id: "obj_celu", texto: "un celular con la pantalla rota en telaraña y 4% de batería", tags: ["urbano"] },
  { id: "obj_riñonera", texto: "una riñonera que nadie deja en el suelo por ningún motivo", tags: ["lumpen"] },
  { id: "obj_sahumerio", texto: "un sahumerio de sándalo que tapa exactamente nada", tags: ["ritual"] },
  { id: "obj_frasco", texto: "un frasco de mermelada con un líquido marrón sin etiqueta", tags: ["ritual", "quimico"] },
  { id: "obj_manta", texto: "una manta polar con dibujos de autitos", tags: ["precario", "infancia"] },
  { id: "obj_balde", texto: "un balde de veinte litros de pintura vacío, reasignado", tags: ["precario", "cuerpo"] },
  { id: "obj_parlante", texto: "un parlante bluetooth con 3% y una responsabilidad enorme", tags: ["social"] },
  { id: "obj_billete", texto: "un billete doblado en ocho hasta el tamaño de una uña", tags: ["quimico", "lumpen"] },
  { id: "obj_cuaderno", texto: "un cuaderno Gloria con anotaciones que no se entienden", tags: ["personal"] },
  { id: "obj_foto", texto: "una foto impresa en papel común, ya despegándose", tags: ["personal", "duelo"] },
  { id: "obj_llavero", texto: "un llavero de un hotel de Mar del Plata que ya no existe", tags: ["personal", "melancolia"] },
  { id: "obj_pañuelo", texto: "un pañuelo blanco que empezó blanco", tags: ["cuerpo"] },
  { id: "obj_pastillero", texto: "un pastillero de días de la semana usado para otras cosas", tags: ["quimico"] },
  { id: "obj_ticket", texto: "un ticket de farmacia con un número de teléfono escrito atrás", tags: ["urbano", "personal"] },
  { id: "obj_piedra", texto: "un cuarzo del que se afirman muchas cosas", tags: ["ritual", "chanta"] },
  { id: "obj_reloj", texto: "un reloj de pulsera parado a las 4:12", tags: ["misterio", "trip"] },
  { id: "obj_guiso", texto: "una olla de guiso que rinde más de lo que debería", tags: ["cuidadora", "social"] }
];

PICHI.FRASES_GURU = [
  "el que busca afuera encuentra el afuera",
  "no hay atajo, pero hay descuento",
  "el ego es un inquilino que no firmó contrato",
  "lo que te molesta del otro es el alquiler de tu propia pieza",
  "todo lo que empieza mal termina, y eso ya es algo",
  "el cuerpo es un colectivo y vos no manejás",
  "el vacío no está vacío, está entre trámites",
  "sanar es acordarse de algo que nunca supiste",
  "la culpa es energía mal facturada",
  "no existe el mañana, existe la cuota",
  "la luz entra por donde te rompieron, si te rompieron bien",
  "el dolor es un maestro pésimo pero es el único que vino",
  "cuando el alumno está listo, el maestro le cobra",
  "hay que morir un poco todos los días, pero con constancia",
  "el karma no castiga, factura",
  "el silencio también miente si lo forzás",
  "soltar no es tirar, es dejar de agarrar",
  "el que llegó al fondo tiene una ventaja: sabe dónde está el piso",
  "nadie se ilumina cómodo",
  "el universo te da señales y vos le pedís subtítulos",
  "todo encuentro es un espejo, y algunos espejos están sucios",
  "la mente es un perro y vos le tirás el palo",
  "no hay camino, hay pisadas, y algunas son tuyas",
  "el que se apura llega antes al mismo lugar equivocado",
  "la abundancia empieza cuando dejás de contar",
  "sos el testigo, no el testimonio",
  "respirá, que es gratis y todavía no lo privatizaron",
  "lo que no se transforma se hereda",
  "el maestro aparece cuando ya no lo necesitás, por eso conviene no necesitarlo nunca",
  "hay preguntas que son respuestas mal escritas",
  "el que sana no ayuda, el que ayuda no sana",
  "la iluminación es una costumbre, no un evento",
  "morir es cambiar de barrio",
  "el presente es lo único que no se puede alquilar",
  "si te dolió, participaste",
  "todo lo que sube baja, incluso vos, sobre todo vos",
  "el amor no se busca, se factura aparte",
  "la verdad es simple, por eso no la vende nadie",
  "no confíes en un maestro que duerma bien",
  "estás exactamente donde tenés que estar, y eso es lo grave"
];
